### ISSUE TITLE
运行main.py --model bert_bilstm_crf_adv --data msra,msr 时报错：

### ISSUE THREAD

**Issue by desfc** [DSXiangLi/ChineseNER#13]

**Comment by desfc** [comment]
报错内容：
………………
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 57 is not in [0, 49)
	 [[{{node task2_msr/crf_layer/GatherV2_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/kg_projects/ChineseNER-bert-bilstm-crf/ChineseNER-main/main.py", line 150, in <module>
    multitask_train(args)
  File "E:/kg_projects/ChineseNER-bert-bilstm-crf/ChineseNER-main/main.py", line 110, in multitask_train
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "C:\Users\return0\.conda\envs\ChineseNER-main\lib\site-packages\tensorflow_estimator\python\estimator\training.py", line 473, in train_and_evaluate
    return executor.run()
………………
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 57 is not in [0, 49)
	 [[node task2_msr/crf_layer/GatherV2_1 (defined at E:\kg_projects\ChineseNER-bert-bilstm-crf\ChineseNER-main\tools\layer.py:126) ]]
………………

**Comment by desfc** [comment]
请问是什么原因呀？

**Comment by desfc** [comment]
感觉出现这个报错的原因是msr数据集
因为多任务NER只要使用msr数据集就会报上面的错
但奇怪的是单任务NER使用msr数据集却不会报错

**Comment by DSXiangLi** [comment]
@fengxuefx 辛苦发一下你的运行脚本吧
