### ISSUE TITLE
def init_params(self)

### ISSUE THREAD

**Issue by copypastejun** [DSXiangLi/ChineseNER#7]
Traceback (most recent call last):
  File "/XXXX/ChineseNER-main/dataset.py", line 131, in <module>
    prep = NerDataset('./data/msra', 100, 10, model_name='bilstm_crf_softlexicon')
  File "/XXXX/ChineseNER-main/dataset.py", line 18, in __init__
    self.init_params()
  File "/XXXX/ChineseNER-main/dataset.py", line 61, in init_params
    with open(os.path.join(self.data_dir, '_'.join(filter(None, [self.prefix, self.surfix, 'data_params.pkl']))), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/msra/giga_softlexicon_data_params.pkl'

**Comment by DSXiangLi** [comment]
之前有运行data/msra/preprocess.py先生成对应的tfrecrod和data_params?

**Comment by copypastejun** [comment]
运行之后又有新的错误
Traceback (most recent call last):
  File "/XXXXX/ChineseNER-main/data/msra/preprocess.py", line 46, in <module>
    prep = get_instance(tokenizer, MAX_SEQ_LEN, TAG2IDX, MAPPING, word_enhance)
  File "/XXXXX/ChineseNER-main/data/base_preprocess.py", line 90, in get_instance
    instance = cls(tokenizer_type, max_seq_len, tag2idx, mapping, **kwargs)
  File "/XXXXX/ChineseNER-main/data/base_preprocess.py", line 142, in __init__
    self.tokenizer = getattr(importlib.import_module('data.tokenizer'), 'get_{}_tokenizer'.format(tokenizer_type))()
  File "/XXXXX/ChineseNER-main/data/tokenizer.py", line 31, in get_giga_tokenizer
    tokenizer = TokenizerAdapter(model)
  File "/XXXXX/ChineseNER-main/data/tokenizer.py", line 53, in __init__
    self.vocab2idx = self.get_vocab2idx()
  File "/XXXXX/ChineseNER-main/data/tokenizer.py", line 59, in get_vocab2idx
    vocab2idx = dict([(word, idx) for idx, word in enumerate(self.model.index2word)])
  File "/anaconda/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 651, in index2word
    "The index2word attribute has been replaced by index_to_key since Gensim 4.0.0.\n"
AttributeError: The index2word attribute has been replaced by index_to_key since Gensim 4.0.0.
See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4

你的版本环境是什么啊
